In [79]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [80]:
df_iris = pd.read_csv('../data/Iris.csv')
df_iris.head()
df_iris.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [81]:
df_iris.info()
df_iris.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
Id               150 non-null int64
SepalLengthCm    150 non-null float64
SepalWidthCm     150 non-null float64
PetalLengthCm    150 non-null float64
PetalWidthCm     150 non-null float64
Species          150 non-null object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.1+ KB


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [82]:
# df_iris.drop()
#don't need ID column
df_iris.drop('Id',axis=1,inplace=True)
df_iris.head(5)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [83]:
#use label encoder to enumerate the type of species
from sklearn.preprocessing import LabelEncoder
#encoding all other features for classification purposes
le = LabelEncoder()
le.fit(df_iris['Species'])
df_iris['Species'] = le.transform(df_iris['Species'])

In [84]:
df_iris.head(5)
list(le.inverse_transform([2, 1, 0]))
#df_iris.drop('Specices',axis=1,inplace=True)
# df_iris.sample(10)
# df_iris.tail(5)

/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


['Iris-virginica', 'Iris-versicolor', 'Iris-setosa']

In [85]:
#normalize data, values between 0 and 1
df_iris_normalized = df_iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']].apply(lambda z: (z - z.min()) / (z.max() - z.min()))
df_iris_normalized['Species'] = df_iris['Species']
df_iris_normalized.tail(5)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
145       0.666667      0.416667       0.711864      0.916667        2
146       0.555556      0.208333       0.677966      0.750000        2
147       0.611111      0.416667       0.711864      0.791667        2
148       0.527778      0.583333       0.745763      0.916667        2
149       0.444444      0.416667       0.694915      0.708333        2

In [86]:
#splitting into train and test datasets using numpy's randn
msk = np.random.rand(len(df_iris_normalized)) < 0.8
train = df_iris_normalized[msk]
test = df_iris_normalized[~msk]
len(train)
len(test)

34

In [87]:
X = train.values[:,:4]
X[:5]
targets = [[1,0,0],[0,1,0],[0,0,1]]
y = np.array([targets[int(x)] for x in train.values[:,4:5]])
y[:5]

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [88]:
#the neural network inputs and the length and width of the species
nninputs = len(X[0])
hidden_neurons = 5
np.random.seed(4)
weight_matrix = 2*np.random.random((nninputs, hidden_neurons)) - 1
weight_matrix

array([[ 0.93405968,  0.0944645 ,  0.94536872,  0.42963199,  0.39545765],
       [-0.56782101,  0.95254891, -0.98753949, -0.49403528, -0.13041694],
       [ 0.55876584, -0.60462985,  0.72598647,  0.96680135, -0.67231552],
       [ 0.19466789, -0.9820278 , -0.22685743, -0.91167988,  0.91330594]])

In [89]:
#three output values, one for each species type
num_outputs = len(y[0])
weight_matrix2 = 2*np.random.random((hidden_layer_neurons, num_outputs)) - 1
weight_matrix2

array([[-0.12770671,  0.89795461,  0.57261197],
       [ 0.7325786 , -0.65366916, -0.85010283],
       [ 0.20148544, -0.66405563,  0.46676034],
       [-0.18311228,  0.05581765,  0.87514317],
       [ 0.04339224, -0.78361323, -0.68355319]])

In [90]:
# sigmoid function
_x = np.linspace( -5, 5, 50 )
_y = 1 / ( 1 + np.exp( -_x ) )

In [91]:
nn_p_rate = 0.2
for epoch in range(50000):
    #non-linear activation function, sigmoid
    sigmoid1 = 1/(1 + np.exp(-(np.dot(X, weight_matrix)))) 
    sigmoid2 = 1/(1 + np.exp(-(np.dot(sigmoid1, weight_matrix2))))
    error_rate = (abs(y - sigmoid2)).mean()
    sigmoid2_delta = (y - sigmoid2)*(sigmoid2 * (1-sigmoid2))
    sigmoid1_delta = sigmoid2_delta.dot(weight_matrix2.T) * (sigmoid1 * (1-sigmoid1))
    weight_matrix2 += sigmoid1.T.dot(sigmoid2_delta) * nn_p_rate
    weight_matrix += X.T.dot(sigmoid1_delta) * nn_p_rate
print('Neural net error rate:', error_rate)

Neural net error rate: 0.04652869622204812


In [92]:
X = test.values[:,:4]
y = np.array([targets[int(x)] for x in test.values[:,4:5]])

l1 = 1/(1 + np.exp(-(np.dot(X, weight_matrix))))
l2 = 1/(1 + np.exp(-(np.dot(l1, weight_matrix2))))

np.round(l2,3)

array([[1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.001, 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 0.692, 0.245],
       [0.   , 0.891, 0.059],
       [0.   , 0.999, 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.997, 0.001],
       [0.   , 0.946, 0.033],
       [0.   , 0.999, 0.001],
       [0.   , 0.901, 0.062],
       [0.   , 0.067, 0.951],
       [0.   , 0.066, 0.95 ],
       [0.   , 0.041, 0.972],
       [0.   , 0.069, 0.95 ],
       [0.   , 0.624, 0.406],
       [0.   , 0.15 , 0.864],
       [0.   , 0.106, 0.906],
       [0.   , 0.067, 0.951],
       [0.   , 0.036, 0.975],
       [0.   , 0.068, 0.946],
       [0.   , 0.078, 0.939],
       [0.

In [97]:
prediction = np.argmax(l2, axis=1) # prediction
res = prediction == np.argmax(y, axis=1)
correct = np.sum(res)/len(res)
#translating back from label encoded values
results = test[['Species']].replace([0,1,2], ['Iris-setosa','Iris-versicolor','Iris-virginica'])

results['Prediction'] = prediction
results['Prediction'] = results['Prediction'].replace([0,1,2], ['Iris-setosa','Iris-versicolor','Iris-virginica'])
print(results)
#all but one in test data match the prediction from the NN

             Species       Prediction
3        Iris-setosa      Iris-setosa
5        Iris-setosa      Iris-setosa
7        Iris-setosa      Iris-setosa
12       Iris-setosa      Iris-setosa
13       Iris-setosa      Iris-setosa
17       Iris-setosa      Iris-setosa
27       Iris-setosa      Iris-setosa
29       Iris-setosa      Iris-setosa
33       Iris-setosa      Iris-setosa
34       Iris-setosa      Iris-setosa
37       Iris-setosa      Iris-setosa
39       Iris-setosa      Iris-setosa
40       Iris-setosa      Iris-setosa
45       Iris-setosa      Iris-setosa
54   Iris-versicolor  Iris-versicolor
61   Iris-versicolor  Iris-versicolor
64   Iris-versicolor  Iris-versicolor
67   Iris-versicolor  Iris-versicolor
81   Iris-versicolor  Iris-versicolor
92   Iris-versicolor  Iris-versicolor
93   Iris-versicolor  Iris-versicolor
94   Iris-versicolor  Iris-versicolor
101   Iris-virginica   Iris-virginica
102   Iris-virginica   Iris-virginica
104   Iris-virginica   Iris-virginica
118   Iris-v